### ISSUE TITLE
Cannot open .apk file containing Chinese characters in name

### ISSUE THREAD

**Issue by hyskylord** [alesimula/wsa_pacman#59]
Hi,
  I just noticed that if the .apk file has name with Chinese characters, it will stuck at loading and I won't be able to install the app. After deleting those characters the .apk file works fine.

**Comment by hyskylord** [comment]
Just notice this is dulplicated. Not sure why it's closed though.

**Comment by hyskylord** [comment]
#31

**Comment by alesimula** [comment]
@hyskylord should be fixed in the latest versions, if it isn't I can't replicate the issue... Could you send me the name of the apk so I can rename one? Maybe it's a specific edge case

**Comment by hyskylord** [comment]
@alesimula The latest version doesn't solve my issue. The apk file just refuse to load whenever I put any Chinese character inside. However, I found that the test version you posted on #31  is working for me.

**Comment by hyskylord** [comment]
As a follow up, I noticed the name "aaaaaa啊.apk" will work correctly with shortname "AAAAAA~1.APK". The name "啊aaaaaa.apk" will give short name "啊AAAA~1.APK" is not working. The name "啊.apk" with null short name is not working.

**Comment by alesimula** [comment]
@hyskylord weird, I thought short names were supposed to be ASCII

**Comment by hyskylord** [comment]
@alesimula NTFS allows Unicode depending on registry settings, and I believe this is enabled by default [Reference](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc781607(v=ws.10)?redirectedfrom=MSDN)

Also the function will return the long path if the file has no short path from MS documentation:
```
If you call GetShortPathName on a path that doesn't have any short names on-disk, the call will succeed, but will return the long-name path instead. This outcome is also possible with NTFS volumes because there's no guarantee that a short name will exist for a given long name.
```

**Comment by hyskylord** [comment]
@akuropka looks like it is enabled by default in Chinese and Japanese systems for some reason, so I guess this is why it doesn't work for some people.

**Comment by alesimula** [comment]
@akuropka @hyskylord I see, I guess I'll also have to check the short name for non-ASCII characters, and use the symlink hack in that case

**Comment by akuropka** [comment]
@alesimula, maybe a stupid question but I did not dig to deep into this, would it not be possible to use a generic link name such as `base.apk -> 你好.apk`?

**Comment by alesimula** [comment]
@hyskylord @akuropka Can anybody confirmed the issue is solved in version 1.3.2 ?

It should now also check whether the short name is ASCII, and use the symlink if not

**Comment by akuropka** [comment]
I can only verify that it still works with ASCII short names.

**Comment by alesimula** [comment]
@hyskylord What about you? Do Chinese apk files work on the new version?

**Comment by akuropka** [comment]
Btw I tried to reproduce the issue by setting the flag `NtfsAllowExtendedCharacterIn8dot3Name` but didn't get Windows to produce a non-ASCII-SFN. The reference is from 2009 and may be outdated. I do have a Windows 10 running in Chinese but it's the standard western version and not the one for the Chinese market (don't know if that makes a difference). I cannot reproduce the issue there as well, so I am out of luck. 😢

**Comment by hyskylord** [comment]
Tried several test files and it seems the problem was fixed. Thank you all for the help. :+1:
